[2024-05-02T02:13:35.720+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T02:13:35.734+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_btc_data.save_bitcoin_data_from_yahoo_api manual__2024-05-02T02:08:30.084206+00:00 [queued]>
[2024-05-02T02:13:35.741+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_btc_data.save_bitcoin_data_from_yahoo_api manual__2024-05-02T02:08:30.084206+00:00 [queued]>
[2024-05-02T02:13:35.741+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-02T02:13:35.752+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_bitcoin_data_from_yahoo_api> on 2024-05-02 02:08:30.084206+00:00
[2024-05-02T02:13:35.759+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2724) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-02T02:13:35.760+0000] {standard_task_runner.py:63} INFO - Started process 2726 to run task
[2024-05-02T02:13:35.760+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_btc_data', 'save_bitcoin_data_from_yahoo_api', 'manual__2024-05-02T02:08:30.084206+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/ingest_btc_data.py', '--cfg-path', '/tmp/tmp8do7ae7n']
[2024-05-02T02:13:35.762+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask save_bitcoin_data_from_yahoo_api
[2024-05-02T02:13:35.795+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_btc_data.save_bitcoin_data_from_yahoo_api manual__2024-05-02T02:08:30.084206+00:00 [running]> on host 30e755686735
[2024-05-02T02:13:35.867+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nononsaa.david@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_btc_data' AIRFLOW_CTX_TASK_ID='save_bitcoin_data_from_yahoo_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T02:08:30.084206+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T02:08:30.084206+00:00'
[2024-05-02T02:13:35.869+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T02:13:36.009+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T02:13:36.010+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_btc_data.py", line 44, in save_btc_data_api_yahoo
    df.to_csv('opt/airflow/dags/btc_eur_data_yahoo_api.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'opt/***/dags'
[2024-05-02T02:13:36.026+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=ingest_btc_data, task_id=save_bitcoin_data_from_yahoo_api, execution_date=20240502T020830, start_date=20240502T021335, end_date=20240502T021336
[2024-05-02T02:13:36.035+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task save_bitcoin_data_from_yahoo_api (Cannot save file into a non-existent directory: 'opt/***/dags'; 2726)
[2024-05-02T02:13:36.054+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T02:13:36.067+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T02:13:36.069+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
